#!/usr/bin/env python3

import argparse
import pulp_config as plpconf

parser = argparse.ArgumentParser(description='Generate PC debug info')

parser.add_argument("--input", dest="input", default=None, help="Specify input file")
parser.add_argument("--output", dest="output", default=None, help="Specify output file")

args = parser.parse_args()

config = plpconf.get_configs_from_env()[0]

l2_size = config.get_int('**/l2/size')


with open(args.output, 'w') as output_file:
  with open(args.input) as input_file:

    script = input_file.read()

    script = script.replace('@l2_size@', l2_size)

    output_file.write(script)